"use client";
import { useMemo, useState } from "react";
import { Activity, ArrowUpRight, Bell, Brain, ChevronRight, Command, FileText, FlaskConical, Gauge, Layers3, Search, Settings, ShieldCheck, Sparkles, Stethoscope, Users, X } from "lucide-react";

type Patient={id:string;name:string;initials:string;procedure:string;day:number;risk:number;trend:number;confidence:number;markers:{name:string;value:number;unit:string;status:"normal"|"watch"|"high"}[];history:number[]};
const PATIENTS:Patient[]=[
{id:"CR-0318",name:"James Kim",initials:"JK",procedure:"Repeat PKP",day:144,risk:72,trend:14,confidence:93,history:[31,38,44,58,72],markers:[{name:"VEGF",value:96,unit:"pg/mL",status:"high"},{name:"IL-6",value:16.4,unit:"pg/mL",status:"high"},{name:"TNF-α",value:12.2,unit:"pg/mL",status:"watch"},{name:"TGF-β",value:24,unit:"ng/mL",status:"watch"}]},
{id:"CR-0241",name:"Alex Morgan",initials:"AM",procedure:"Primary DMEK",day:92,risk:18,trend:-6,confidence:96,history:[36,30,26,22,18],markers:[{name:"VEGF",value:31,unit:"pg/mL",status:"normal"},{name:"IL-6",value:5.1,unit:"pg/mL",status:"normal"},{name:"TNF-α",value:3.9,unit:"pg/mL",status:"normal"},{name:"TGF-β",value:39,unit:"ng/mL",status:"normal"}]},
{id:"CR-0196",name:"Rina Shah",initials:"RS",procedure:"Primary DSAEK",day:61,risk:41,trend:4,confidence:90,history:[28,31,33,37,41],markers:[{name:"VEGF",value:57,unit:"pg/mL",status:"watch"},{name:"IL-6",value:9.1,unit:"pg/mL",status:"watch"},{name:"TNF-α",value:7,unit:"pg/mL",status:"watch"},{name:"TGF-β",value:30,unit:"ng/mL",status:"normal"}]}
];

function Twin({risk,sim}:{risk:number;sim:number}){const projected=Math.max(8,Math.round(risk-sim*0.42));return <div className="twinShell"><div className="halo h1"/><div className="halo h2"/><div className="halo h3"/><div className="orbit"><span/><span/><span/></div><div className="twinCore"><div className="coreGlow"/><strong>{projected}%</strong><small>projected risk</small></div><div className="twinLabel t1">IMMUNE<br/><b>{risk>60?"ACTIVE":"CONTROLLED"}</b></div><div className="twinLabel t2">ENDOTHELIUM<br/><b>{risk>60?"DECLINING":"STABLE"}</b></div><div className="twinLabel t3">CYTOKINES<br/><b>{risk>60?"ELEVATED":"BALANCED"}</b></div></div>}
function Line({values}:{values:number[]}){const pts=values.map((v,i)=>`${(i/(values.length-1))*100},${100-v}`).join(" ");return <svg className="line" viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" x2="1"><stop stopColor="#76f7d2"/><stop offset="1" stopColor="#7aa2ff"/></linearGradient></defs><polyline points={pts} fill="none" stroke="url(#g)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>}

export default function Page(){
 const [selected,setSelected]=useState(0); const [sim,setSim]=useState(0); const [cmd,setCmd]=useState(false); const [mode,setMode]=useState<"clinical"|"research">("clinical");
 const p=PATIENTS[selected]; const projected=Math.max(8,Math.round(p.risk-sim*0.42));
 const insight=useMemo(()=>p.risk>60?"The current trajectory suggests accelerated immune activation. Rising VEGF and IL-6 are the dominant contributors. Consider endothelial imaging and repeat biomarker assessment within 14 days.":p.risk>30?"A moderate inflammatory shift is present. Current findings support closer interval monitoring and correlation with graft imaging.":"The graft profile remains stable. Biomarkers and longitudinal risk are moving in a favorable direction.",[p]);
 return <main>
  <aside className="rail">
   <div className="brand"><div className="mark">A</div><div><strong>AURELIA</strong><span>Clinical Intelligence OS</span></div></div>
   <nav><button className={mode==="clinical"?"active":""} onClick={()=>setMode("clinical")}><Stethoscope/>Clinical</button><button className={mode==="research"?"active":""} onClick={()=>setMode("research")}><FlaskConical/>Research</button><button><Users/>Cohorts</button><button><ShieldCheck/>Governance</button></nav>
   <div className="railBottom"><button onClick={()=>setCmd(true)}><Command/>Command</button><button><Settings/>Settings</button><div className="profile"><span>PH</span><div><b>Pham Huy</b><small>Clinical Researcher</small></div></div></div>
  </aside>
  <section className="workspace">
   <header><button className="search" onClick={()=>setCmd(true)}><Search/>Search patients, cohorts, reports <kbd>⌘ K</kbd></button><div className="headerActions"><span className="live"><i/>SYSTEM ONLINE</span><button className="icon"><Bell/></button></div></header>
   {mode==="clinical"?<>
   <div className="patientBar"><div className="patientIdentity"><span className="avatar">{p.initials}</span><div><p>{p.id} · POST-OP DAY {p.day}</p><h1>{p.name}</h1><span>{p.procedure}</span></div></div><div className="patientSwitch">{PATIENTS.map((x,i)=><button key={x.id} className={i===selected?"selected":""} onClick={()=>{setSelected(i);setSim(0)}}>{x.initials}</button>)}</div><button className="report"><FileText/>Generate report</button></div>
   <div className="heroGrid">
    <section className="twinPanel"><div className="panelTop"><div><span className="eyebrow">PATIENT DIGITAL TWIN</span><h2>Live graft state</h2></div><span className="confidence"><Sparkles/> {p.confidence}% confidence</span></div><Twin risk={p.risk} sim={sim}/><div className="twinFooter"><span><i className="green"/>Corneal barrier</span><span><i className="blue"/>Endothelium</span><span><i className="coral"/>Immune response</span></div></section>
    <section className="insightPanel"><div className="panelTop"><div><span className="eyebrow">SYSTEM ASSESSMENT</span><h2>Clinical insight</h2></div><Brain/></div><p className="insight">{insight}</p><div className="drivers"><div><span>Primary driver</span><b>{p.risk>60?"VEGF elevation":"Stable endothelial profile"}</b></div><div><span>Trajectory</span><b className={p.trend>0?"bad":"good"}>{p.trend>0?"+":""}{p.trend}% / 30d</b></div><div><span>Model confidence</span><b>{p.confidence}%</b></div></div><button className="deep">Open full reasoning <ArrowUpRight/></button></section>
   </div>
   <div className="lowerGrid">
    <section className="trajectory"><div className="panelTop"><div><span className="eyebrow">LONGITUDINAL INTELLIGENCE</span><h2>Risk trajectory</h2></div><strong className={p.risk>60?"risk high":p.risk>30?"risk mid":"risk low"}>{p.risk}%</strong></div><div className="chart"><div className="gridLines"/><Line values={p.history}/></div><div className="axis"><span>May</span><span>Jun</span><span>Jul</span><span>Now</span></div></section>
    <section className="markers"><div className="panelTop"><div><span className="eyebrow">LIVE BIOMARKERS</span><h2>Signal matrix</h2></div><Activity/></div><div className="markerGrid">{p.markers.map(m=><div key={m.name} className={`marker ${m.status}`}><span>{m.name}</span><strong>{m.value}</strong><small>{m.unit}</small></div>)}</div></section>
   </div>
   <section className="simulation"><div><span className="eyebrow">SIMULATION LAB</span><h2>Treatment scenario</h2><p>Explore how a hypothetical reduction in inflammatory load could alter the projected trajectory.</p></div><div className="simControl"><div><span>Intervention intensity</span><b>{sim}%</b></div><input type="range" min="0" max="70" value={sim} onChange={e=>setSim(Number(e.target.value))}/><div className="simResult"><span>Current <b>{p.risk}%</b></span><ChevronRight/><span>Projected <b>{projected}%</b></span></div></div></section>
   </>:<Research/>}
  </section>
  {cmd&&<div className="overlay" onClick={()=>setCmd(false)}><div className="commandBox" onClick={e=>e.stopPropagation()}><div className="commandSearch"><Search/><input autoFocus placeholder="Search or run a command..."/><button onClick={()=>setCmd(false)}><X/></button></div><div className="commandList"><span>QUICK ACTIONS</span>{["Open patient workspace","Compare latest visits","Generate clinical report","Open Research Studio","Export cohort dataset"].map((x,i)=><button key={x}><i>{i+1}</i>{x}<ChevronRight/></button>)}</div></div></div>}
 </main>
}

function Research(){return <div className="researchView"><div className="researchHero"><div><span className="eyebrow">RESEARCH STUDIO</span><h1>Evidence, not decoration.</h1><p>Model performance, cohort behavior and explainability in one controlled research environment.</p></div><button><FileText/>Export research brief</button></div><div className="researchGrid"><Metric title="AUROC" value="0.842" note="95% CI 0.79–0.89"/><Metric title="Sensitivity" value="88.1%" note="At selected threshold"/><Metric title="Calibration" value="0.118" note="Brier score"/><Metric title="Cohort" value="1,248" note="Validated observations"/></div><div className="researchCharts"><section><span className="eyebrow">DISCRIMINATION</span><h2>ROC performance</h2><svg viewBox="0 0 100 100"><line x1="0" y1="100" x2="100" y2="0" className="diag"/><polyline points="0,100 8,68 18,45 34,26 56,13 78,6 100,0"/></svg></section><section><span className="eyebrow">SURVIVAL</span><h2>Kaplan–Meier</h2><svg viewBox="0 0 100 100"><polyline points="0,6 18,6 18,14 35,14 35,23 52,23 52,38 70,38 70,58 86,58 86,76 100,76"/></svg></section></div></div>}
function Metric({title,value,note}:{title:string;value:string;note:string}){return <div className="metric"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>}
